"use client"

import {
  Clock,
  ArrowUpRight,
  BookOpen,
  TrendingUp,
  Brain,
  Lightbulb,
  Cpu,
  BarChart3,
} from "lucide-react"
import { Button } from "@/components/ui/button"

const articles = [
  {
    icon: Brain,
    category: "AI & Strategy",
    title: "How Generative AI Is Reshaping Corporate Strategy",
    excerpt:
      "Exploring the paradigm shift as AI moves from operational tool to strategic differentiator in C-suite decision making.",
    readTime: "8 min read",
    date: "Feb 2026",
    featured: true,
  },
  {
    icon: BarChart3,
    category: "Execution",
    title: "The Execution Gap: Why 67% of Strategies Fail",
    excerpt:
      "New research reveals systemic causes behind strategy-execution disconnects and a framework for bridging the gap.",
    readTime: "6 min read",
    date: "Jan 2026",
    featured: false,
  },
  {
    icon: Lightbulb,
    category: "Org Design",
    title: "Network Organizations: Beyond the Matrix",
    excerpt:
      "Moving past traditional hierarchies to dynamic organizational forms that enable adaptive capability at scale.",
    readTime: "10 min read",
    date: "Jan 2026",
    featured: false,
  },
  {
    icon: TrendingUp,
    category: "Compensation",
    title: "Pay Transparency Legislation: Global Impact Analysis",
    excerpt:
      "An AI-assisted review of emerging pay transparency regulations and their implications for total rewards strategy.",
    readTime: "7 min read",
    date: "Dec 2025",
    featured: false,
  },
  {
    icon: Cpu,
    category: "Talent",
    title: "Building AI-Native Talent Pipelines",
    excerpt:
      "How forward-thinking organizations are redesigning talent acquisition and development for the AI era.",
    readTime: "5 min read",
    date: "Dec 2025",
    featured: false,
  },
]

export function KnowledgeHub() {
  const featured = articles[0]
  const rest = articles.slice(1)

  return (
    <section id="about" className="px-6 py-24">
      <div className="mx-auto max-w-7xl">
        <div className="mb-16 text-center">
          <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-border bg-secondary/50 px-4 py-1.5 text-sm font-medium text-muted-foreground">
            <BookOpen className="h-3.5 w-3.5 text-primary" />
            Knowledge Hub
          </div>
          <h2 className="mb-4 text-balance text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
            AI-Curated Insights
          </h2>
          <p className="mx-auto max-w-2xl text-pretty text-muted-foreground">
            Research papers, thought leadership, and data-driven analysis
            generated by our advisory team and AI intelligence engine.
          </p>
        </div>

        <div className="grid gap-6 lg:grid-cols-2">
          {/* Featured article */}
          <div className="group relative overflow-hidden rounded-2xl border border-border bg-card p-8 transition-all duration-300 hover:border-primary/30 hover:shadow-lg hover:shadow-primary/5 lg:row-span-2">
            <div className="mb-6 flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary">
                <featured.icon className="h-5 w-5" />
              </div>
              <span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-medium text-primary">
                Featured
              </span>
            </div>

            <span className="mb-3 block text-xs font-medium uppercase tracking-wider text-primary">
              {featured.category}
            </span>
            <h3 className="mb-4 text-2xl font-bold leading-tight text-foreground">
              {featured.title}
            </h3>
            <p className="mb-6 text-muted-foreground leading-relaxed">
              {featured.excerpt}
            </p>

            <div className="mt-auto flex items-center justify-between">
              <div className="flex items-center gap-4 text-xs text-muted-foreground">
                <span className="flex items-center gap-1.5">
                  <Clock className="h-3.5 w-3.5" />
                  {featured.readTime}
                </span>
                <span>{featured.date}</span>
              </div>
              <ArrowUpRight className="h-4 w-4 text-muted-foreground opacity-0 transition-all group-hover:opacity-100 group-hover:text-primary" />
            </div>
          </div>

          {/* Article list */}
          {rest.map((article) => (
            <div
              key={article.title}
              className="group flex gap-5 overflow-hidden rounded-2xl border border-border bg-card p-6 transition-all duration-300 hover:border-primary/30 hover:shadow-lg hover:shadow-primary/5"
            >
              <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary">
                <article.icon className="h-5 w-5" />
              </div>
              <div className="flex-1">
                <span className="mb-1.5 block text-xs font-medium uppercase tracking-wider text-primary">
                  {article.category}
                </span>
                <h3 className="mb-2 text-base font-semibold text-foreground leading-snug">
                  {article.title}
                </h3>
                <p className="mb-3 text-sm text-muted-foreground line-clamp-2">
                  {article.excerpt}
                </p>
                <div className="flex items-center gap-4 text-xs text-muted-foreground">
                  <span className="flex items-center gap-1.5">
                    <Clock className="h-3 w-3" />
                    {article.readTime}
                  </span>
                  <span>{article.date}</span>
                </div>
              </div>
              <ArrowUpRight className="h-4 w-4 shrink-0 self-start text-muted-foreground opacity-0 transition-all group-hover:opacity-100 group-hover:text-primary" />
            </div>
          ))}
        </div>

        <div className="mt-10 text-center">
          <Button
            variant="outline"
            className="border-border text-foreground hover:bg-secondary gap-2"
          >
            View All Insights
            <ArrowUpRight className="h-4 w-4" />
          </Button>
        </div>
      </div>
    </section>
  )
}
